name: Release VSIX

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run compile

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Determine version
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "TAG=v$VERSION" >> "$GITHUB_ENV"

      - name: Package VSIX
        run: |
          mkdir -p releases
          vsce package --allow-missing-repository --skip-license --out releases/markdown-preview-panel-${VERSION}.vsix

      - name: Upload VSIX asset (release event)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: releases/markdown-preview-panel-${{ env.VERSION }}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload VSIX artifact
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: markdown-preview-panel-${{ env.VERSION }}
          path: releases/markdown-preview-panel-${{ env.VERSION }}.vsix

      - name: Upload VSIX asset (push/manual)
        if: github.event_name != 'release'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Markdown Sidebar Panel Previewer v${{ env.VERSION }}
          draft: false
          prerelease: false
          files: releases/markdown-preview-panel-${{ env.VERSION }}.vsix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
